### ISSUE TITLE
Is unity necessary?

### ISSUE THREAD

**Issue by alexfrom0815** [princeton-vl/PackIt#16]
Hello, I think PackIt is a very meaningful job. I want to know if installing unity is necessary for PackIt's training/visualization/heuristics/debugging? My Linux environment have not installed Unity, but the file 'main_heuristic.py' still runs.

**Comment by imankgoyal** [comment]
Hi, thanks for your interest in our work. I do not think installing Unity is necessary for training and testing purposes. However, if you want to modify the environment, then it would be required. So the requirement for Unity would depend on the use case.
