### ISSUE TITLE
Can it work for Bin Packing Problem?

### ISSUE THREAD

**Issue by only-changer** [princeton-vl/PackIt#8]
I am new to this area, I wonder if PackIt can be used to solve the 3D Bin Packing Problem? 
What is the difference between the problem the PackIt solves and the problem of  3D Bin Packing?

Thanks.

**Comment by imankgoyal** [comment]
Hello,

Thanks for you interest in our work. The packing problem in PackIt is a variant of 3D Bin Packing problem. Following are the major difference in my view:

-- What matter in standard bin packing is the size of the object. There is no notion of shape of an object. The volume occupied by two objects is equal to the sum of the volume of two objects. This is not the case with PackIt. There is a significant emphasis on the shape and how to put shapes together in PackIt. In PackIt two objects might "perfectly fit" or there could be empty space while putting them together. Hence the volume occupied when two objects are together would be more than the individual volumes. 

-- Standard bin packing asks the question: `find the minimum number of boxes required to pack some objects together`. While in PackIt, the question asked in can the following objects be put in the given box.  

I think an extension/variant on PackIt can be used to solve the variant of 3D Bin Packing Problem you might be interested in.

Best,
Ankit

**Comment by only-changer** [comment]
Ok, I got it. Thank you~
